# Appointment statuses
APPOINTMENT_SCHEDULED = 0
PATIENT_CHECKED_IN = 1
APPOINTMENT_FINISHED = 2

# Voucher statuses
VOUCHER_CREATED = 0
VOUCHER_USED = 1
VOUCHER_PAID = 2

# Ride statuses
RIDE_INITIATED = 0
RIDE_IN_TRANSIT = 1
RIDE_COMPLETED = 2
PAYMENT_PENDING = 0
PAYMENT_COMPLETED = 1